name: my_travel_guide
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^0.13.0+1
  device_info: ^0.4.1+4
  font_awesome_flutter: ^8.5.0
  google_maps_flutter: ^0.5.21+15
  location_permissions: ^2.0.4+1
  location: ^2.3.5
  flutter_auth_buttons: ^0.6.0
  carousel_slider: ^1.4.1
  timeline_list: ^0.0.3
  settings_ui: ^0.2.0
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.4
  rxdart: ^0.23.1
  fluttertoast: ^3.1.3
  google_maps_webservice: ^0.0.16
  place_picker: ^0.9.11
  http: ^0.12.0+4
  google_maps_place_picker: ^0.5.1
  date_format: ^1.0.8
  firebase_remote_config: ^0.3.0+1
  shared_preferences: ^0.5.6+1
  video_player: ^0.10.7
  path_provider: ^1.6.0
  path: ^1.6.4
  image_picker: ^0.6.3+1
  flutter_launcher_icons: ^0.7.0
  fancy_dialog: ^1.0.3
  giffy_dialog: ^1.7.0
  outline_material_icons: ^0.1.1
  simple_animations: ^1.3.3
  page_transition: ^1.1.4
  url_launcher: ^5.4.2

  firebase_admob: ^0.5.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - .env
    - assets/images/sign_in_page_bg.jpg
    - assets/images/logo_white.png
    - assets/images/options.png
    - assets/images/near_by_landmarks.png
    - assets/images/timeline.png
    - assets/images/timeline_cropped.png
    - assets/images/sphinx.jpg
    - assets/images/petra.jpg
    - assets/images/test.jpg
    - assets/images/jerusalem.jpg
    - assets/images/camera.png
    - assets/images/pyramids.jpg
    - assets/images/trevi.jpg
    - assets/images/information.png
    - assets/images/search.png
    - assets/images/map.png
    - assets/images/add_location.png
    - assets/images/google_logo.png
    - assets/videos/simple.mp4
    - assets/maps_style.json
    - assets/launcher/ic_launcher.png
    - assets/locales/en.json
    - assets/locales/sk.json


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pompiere
      fonts:
        - asset: fonts/Pompiere-Regular.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
